version: "3.9"  # optional since v1.27.0


services:
  web:
    build: .
    command: python run.py
    volumes:
      - .:/Dbanks-master
    ports:
      - 127.0.0.1:8090:8090
    # depends_on:
    #   - db
  # db:
  #   image: postgres:13
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/

# volumes:
#   postgres_data: