"""update pago

Revision ID: 8965a89bceab
Revises: 50d72e8fb332
Create Date: 2022-04-05 15:04:47.714061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8965a89bceab'
down_revision = '50d72e8fb332'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbextrato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parcelas_paga', sa.String(length=4), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbextrato', schema=None) as batch_op:
        batch_op.drop_column('parcelas_paga')

    # ### end Alembic commands ###
