"""Initial migration.

Revision ID: d58f54e263c1
Revises: 
Create Date: 2022-02-10 10:11:33.388633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd58f54e263c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('login', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('tbcadastro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('fone', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbextrato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('loja', sa.String(length=100), nullable=True),
    sa.Column('parcela', sa.String(length=4), nullable=True),
    sa.Column('valor', sa.Numeric(precision=8, asdecimal=False), nullable=True),
    sa.Column('nome_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['nome_id'], ['tbcadastro.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbextrato_nome_id'), 'tbextrato', ['nome_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tbextrato_nome_id'), table_name='tbextrato')
    op.drop_table('tbextrato')
    op.drop_table('tbcadastro')
    op.drop_table('admin_user')
    # ### end Alembic commands ###
